[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true

[theme]
base = "light"
primaryColor = "#147d64"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f5f6"
textColor = "#25292d"
